# Generated by Django 4.2.3 on 2023-07-18 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 23, 3, 16, 758045), verbose_name='дата истечения'),
        ),
    ]
